version: '3.3'

services:
  localstack:
    image: localstack/localstack:0.12.0
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
    volumes:
      - "./scripts/localstack:/docker-entrypoint-initaws.d"





